name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetch all branches
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Set up rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          # Check if gh-pages branch exists
          if ! git show-ref --quiet refs/origin/gh-pages; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git rm -rf . || true
            echo "# Documentation" > README.md
            git add README.md
            git commit -m "Initial gh-pages commit"
            git push origin gh-pages
            git checkout main
          fi

          # Sync with main branch
          git checkout gh-pages
          git merge -m 'Merge main' main --allow-unrelated-histories || {
            echo "Merge failed, trying reset..."
            git reset --hard origin/main
          }

          # venv required by maturin
          python3 -m venv .venv
          source .venv/bin/activate

          make install-test-requirements
          make install-doc-requirements
          # Required for pdoc to be able to import the sources
          make dev-install
          make doc

          git add -f docs
          git commit -m "Re-generated documentation" --allow-empty
          git push origin gh-pages
